apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: deployment
  name: deployment
spec:
  containers:
  - args:
    - niginx1
    image: nginx:1.16
    name: deployment
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
