apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal.server: | # you may select any name here, but it must end with the .server file extension
    internal.com:53 {
        errors
        cache 30
        forward . 10.0.0.10 10.240.0.20 10.240.0.37 # Your internal DNS server(s)
    }
